# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Common\UserBundle\Entity\User:
            #algorytm hashowania hasła
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        blog_users:
            entity:
                class: CommonUserBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: blog_users
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login
                target_path_parameter: /
                default_target_path: /
            logout: { path: /logout, target: /login }

    access_control:
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
